const {test} = require('node:test')
const assert = require('node:assert/strict')
const {runtime} = require('./helpers/runtime.cjs')
const guestStorage = () => new Map([['chagok.guest.v1','true'],['chagok.auth','real-session-sentinel']])
const forbiddenFetch = () => { throw new Error('Guest contacted backend') }
test('guest starts as a ready resident without login and never reaches backend',async()=>{
 const rt=runtime(false,forbiddenFetch,guestStorage()),auth=rt.load('src/api/auth.ts')
 const me=await auth.getMe()
 assert.equal(me.building.role,'RESIDENT');assert.equal(me.onboarding_step,'DONE')
 assert.equal((await rt.load('src/api/parking.ts').getHome()).building.role,'RESIDENT')
 assert.equal((await rt.load('src/api/sharedParking.ts').listGarages()).items.length>0,true)
 await assert.rejects(rt.load('src/api/admin.ts').getAdminDashboard(3),e=>e.status===403)
 await assert.rejects(auth.login({email:'admin@kw.ac.kr',password:'chagok1234'}),e=>e.status===403)
 await assert.rejects(rt.load('src/api/client.ts').request('POST','/anything'),e=>e.status===403)
 assert.equal(rt.storage.get('chagok.auth'),'real-session-sentinel')
})
test('parking, vehicles, profile and schedules survive a page reload',async()=>{
 const storage=guestStorage(),rt=runtime(false,forbiddenFetch,storage)
 const auth=rt.load('src/api/auth.ts'),parking=rt.load('src/api/parking.ts'),vehicles=rt.load('src/api/vehicles.ts')
 await auth.updateMe({name:'체험 입주민'})
 await parking.putRecurringSchedule(7,{days:['SAT'],time:'09:30',memo:'체험 일정'})
 await parking.readAllNotifications()
 const vehicle=await vehicles.createMyVehicle({plate:'99가 1234',alias:'체험 차량'})
 const entered=await parking.createParking({vehicle_id:vehicle.id,slot_id:1002,expected_exit_at:'2099-10-09T22:00:00+09:00'})
 const second=runtime(false,forbiddenFetch,storage)
 assert.equal((await second.load('src/api/auth.ts').getMe()).name,'체험 입주민')
 assert.equal((await second.load('src/api/vehicles.ts').listMyVehicles()).items.some(item=>item.id===vehicle.id),true)
 const home=await second.load('src/api/parking.ts').getHome()
 assert.equal(home.my_parking.parking_id,entered.id)
 assert.equal((await second.load('src/api/parking.ts').getRecurringSchedule(7)).time,'09:30')
 assert.equal(home.unread_notification_count,0)
 const next=await second.load('src/api/vehicles.ts').createMyVehicle({plate:'98가 4321'})
 assert.equal(next.id>vehicle.id,true)
 assert.equal(storage.get('chagok.auth'),'real-session-sentinel')
})
test('a newly submitted request and acceptance survive reload with a single token deduction',async()=>{
 const storage=guestStorage(),rt=runtime(false,forbiddenFetch,storage)
 const api=rt.load('src/api/sharedParking.ts'),auth=rt.load('src/api/auth.ts')
 const date=rt.load('src/mocks/sharedParking.ts').SHARED_MOCK_DATE
 const balance=(await auth.getMe()).token_balance
 const created=await api.createShareRequest({offer_id:501,vehicle_id:7,request_date:date,start_hour:7,end_hour:8})
 assert.equal(created.status,'PENDING')
 const reloaded=runtime(false,forbiddenFetch,storage),api2=reloaded.load('src/api/sharedParking.ts')
 assert.equal((await api2.getShareRequest(created.id)).status,'PENDING')
 await api2.previewGuestShareResult(created.id,'APPROVED')
 await assert.rejects(api2.previewGuestShareResult(created.id,'APPROVED'),e=>e.status===409)
 const again=runtime(false,forbiddenFetch,storage)
 assert.equal((await again.load('src/api/sharedParking.ts').getShareRequest(created.id)).status,'APPROVED')
 assert.equal((await again.load('src/api/auth.ts').getMe()).token_balance,balance-created.total_price)
})
test('rejection is persistent and does not debit tokens; real mode rejects demo result',async()=>{
 const storage=guestStorage(),rt=runtime(false,forbiddenFetch,storage)
 const api=rt.load('src/api/sharedParking.ts'),auth=rt.load('src/api/auth.ts')
 const balance=(await auth.getMe()).token_balance
 await api.previewGuestShareResult(701,'REJECTED')
 const again=runtime(false,forbiddenFetch,storage)
 assert.equal((await again.load('src/api/sharedParking.ts').getShareRequest(701)).status,'REJECTED')
 assert.equal((await again.load('src/api/auth.ts').getMe()).token_balance,balance)
 await assert.rejects(runtime(false,forbiddenFetch).load('src/api/sharedParking.ts').previewGuestShareResult(701,'APPROVED'),e=>e.status===403)
})

test('entry, reset and exit reload at the right screen and preserve actual authentication',async()=>{
 const storage=guestStorage()
 storage.set('chagok.guest.state.v1',JSON.stringify({version:1,data:{userShareRequests:[]}}))
 storage.set('chagok.guest.session.v1','demo-only')
 let reloads=0
 const window={location:{hash:'',reload:()=>reloads++}}
 const mode=runtime(false,forbiddenFetch,storage,window).load('src/api/guestMode.ts')
 mode.resetGuestDemo()
 assert.equal(window.location.hash,'#home')
 assert.equal(storage.has('chagok.guest.state.v1'),false)
 assert.equal(storage.has('chagok.guest.session.v1'),false)
 assert.equal((await runtime(false,forbiddenFetch,storage).load('src/api/sharedParking.ts').listMyShareRequests()).items.length,3)
 mode.exitGuestDemo()
 assert.equal(window.location.hash,'#welcome')
 assert.equal(storage.has('chagok.guest.v1'),false)
 assert.equal(runtime(false,forbiddenFetch,storage).load('src/api/client.ts').USE_MOCK,false)
 mode.startGuestDemo()
 assert.equal(window.location.hash,'#home')
 assert.equal(storage.get('chagok.guest.v1'),'true')
 assert.equal(reloads,3)
 assert.equal(storage.get('chagok.auth'),'real-session-sentinel')
})
test('guest acceptance checks balance and overlapping reservations without changing pending state',async()=>{
 const storage=guestStorage(),rt=runtime(false,forbiddenFetch,storage)
 const api=rt.load('src/api/sharedParking.ts'),auth=rt.load('src/api/auth.ts')
 const balance=(await auth.getMe()).token_balance
 // Make the pending request overlap the accepted example.
 rt.load('src/mocks/sharedParking.ts').userShareRequests[0].start_hour=18
 rt.load('src/mocks/sharedParking.ts').userShareRequests[0].end_hour=19
 await assert.rejects(api.previewGuestShareResult(701,'APPROVED'),e=>e.status===409)
 assert.equal((await api.getShareRequest(701)).status,'PENDING')
 assert.equal((await auth.getMe()).token_balance,balance)
 const data=rt.load('src/mocks/sharedParking.ts')
 data.userShareRequests.push({...data.userShareRequests[0],id:900,start_hour:7,end_hour:8,total_price:balance+1})
 await assert.rejects(api.previewGuestShareResult(900,'APPROVED'),e=>e.status===409)
 assert.equal((await api.getShareRequest(900)).status,'PENDING')
 assert.equal((await auth.getMe()).token_balance,balance)
})

test('role selection enters the chosen screen and never changes actual authentication',async()=>{
 const storage=new Map([['chagok.auth','real-session-sentinel']])
 let reloads=0
 const window={location:{hash:'',reload:()=>reloads++}}
 const mode=runtime(false,forbiddenFetch,storage,window).load('src/api/guestMode.ts')
 mode.startGuestDemo('ADMIN')
 assert.equal(window.location.hash,'#admin')
 assert.equal(storage.get('chagok.guest.role.v1'),'ADMIN')
 const admin=runtime(false,forbiddenFetch,storage)
 assert.equal((await admin.load('src/api/auth.ts').getMe()).building.role,'ADMIN')
 assert.equal(admin.load('src/api/auth.ts').getMyRole(),'ADMIN')
 assert.equal((await admin.load('src/api/parking.ts').getHome()).building.role,'ADMIN')
 assert.equal((await admin.load('src/api/admin.ts').getAdminDashboard(3)).pending_requests.length,4)
 mode.exitGuestDemo()
 assert.equal(window.location.hash,'#welcome')
 assert.equal(storage.has('chagok.guest.v1'),false)
 assert.equal(runtime(false,forbiddenFetch,storage).load('src/api/client.ts').USE_MOCK,false)
 mode.startGuestDemo('RESIDENT')
 assert.equal(window.location.hash,'#home')
 assert.equal((await runtime(false,forbiddenFetch,storage).load('src/api/auth.ts').getMe()).building.role,'RESIDENT')
 assert.equal(storage.get('chagok.auth'),'real-session-sentinel')
 assert.equal(reloads,3)
 assert.throws(()=>mode.startGuestDemo('OWNER'))
})

test('admin request decisions, slot settings and share offer CRUD survive reload without server calls',async()=>{
 const storage=guestStorage()
 storage.set('chagok.guest.role.v1','ADMIN')
 let calls=0
 const fetch=()=>{calls++;throw new Error('Unexpected server call')}
 const rt=runtime(false,fetch,storage),api=rt.load('src/api/admin.ts')
 const original=(await api.listAdminShareOffers(3)).items.length
 await api.decideShareRequest(303,{status:'APPROVED'})
 await api.decideShareRequest(301,{status:'REJECTED',reject_reason:'예시 시간 조정 필요'})
 await api.updateAdminSlot(1008,{is_active:true})
 const created=(await api.createAdminShareOffer(3,{slot_ids:[1005],weekdays:['MON','WED'],start_hour:9,end_hour:18,hourly_price:3,max_hours:2,memo:'체험용 조건'})).items[0]
 await api.updateAdminShareOffer(created.id,{hourly_price:7,is_public:false})
 await api.deleteAdminShareOffer(401)
 const second=runtime(false,fetch,storage),api2=second.load('src/api/admin.ts')
 const requests=await api2.listAdminShareRequests(3)
 assert.equal(requests.items.find(item=>item.id===303).status,'APPROVED')
 assert.equal(requests.items.find(item=>item.id===301).status,'REJECTED')
 assert.equal(second.load('src/mocks/admin.ts').shareRequests.find(item=>item.id===301).reject_reason,'예시 시간 조정 필요')
 assert.equal(requests.items.some(item=>item.id===302 || item.id===304),false)
 assert.equal((await api2.listAdminSlots(3)).items.find(slot=>slot.slot_id===1008).is_active,true)
 const layout=await second.load('src/api/parking.ts').getBuildingLayout(3)
 assert.equal(layout.zones.flatMap(zone=>zone.slots).find(slot=>slot.id===1008).is_active,true)
 const offers=(await api2.listAdminShareOffers(3)).items
 assert.equal(offers.length,original)
 assert.equal(offers.some(offer=>offer.id===401),false)
 assert.equal(offers.find(offer=>offer.id===created.id).hourly_price,7)
 assert.equal(offers.find(offer=>offer.id===created.id).is_public,false)
 assert.equal(offers.find(offer=>offer.id===created.id).memo,'체험용 조건')
 await assert.rejects(api2.decideShareRequest(303,{status:'APPROVED'}),e=>e.status===409)
 const next=(await api2.createAdminShareOffer(3,{slot_ids:[1008],start_hour:9,end_hour:18})).items[0]
 assert.equal(next.id>created.id,true)
 await assert.rejects(api2.getAdminDashboard(999),e=>e.status===403)
 assert.equal(storage.get('chagok.auth'),'real-session-sentinel')
 assert.equal(calls,0)
})

test('resident and administrator state remains independent across role changes and re-entry',async()=>{
 const storage=guestStorage()
 const window={location:{hash:'',reload:()=>{}}}
 const resident=runtime(false,forbiddenFetch,storage,window)
 await resident.load('src/api/auth.ts').updateMe({name:'입주민 진행 상태'})
 await resident.load('src/api/sharedParking.ts').previewGuestShareResult(701,'REJECTED')
 const residentState=storage.get('chagok.guest.state.v1')
 const residentSession=storage.get('chagok.guest.session.v1')
 resident.load('src/api/guestMode.ts').exitGuestDemo()
 resident.load('src/api/guestMode.ts').startGuestDemo('ADMIN')
 const admin=runtime(false,forbiddenFetch,storage,window)
 await admin.load('src/api/auth.ts').updateMe({name:'관리자 진행 상태'})
 await admin.load('src/api/admin.ts').updateAdminSlot(1008,{is_active:true})
 await admin.load('src/api/admin.ts').decideShareRequest(303,{status:'REJECTED',reject_reason:'관리자 체험'})
 assert.equal(storage.get('chagok.guest.state.v1'),residentState)
 assert.equal(storage.get('chagok.guest.session.v1'),residentSession)
 admin.load('src/api/guestMode.ts').exitGuestDemo()
 admin.load('src/api/guestMode.ts').startGuestDemo('RESIDENT')
 const residentAgain=runtime(false,forbiddenFetch,storage,window)
 assert.equal((await residentAgain.load('src/api/auth.ts').getMe()).name,'입주민 진행 상태')
 assert.equal((await residentAgain.load('src/api/sharedParking.ts').getShareRequest(701)).status,'REJECTED')
 const layout=await residentAgain.load('src/api/parking.ts').getBuildingLayout(3)
 assert.equal(layout.zones.flatMap(zone=>zone.slots).find(slot=>slot.id===1008).is_active,false)
 assert.equal(residentAgain.load('src/mocks/admin.ts').shareRequests.find(item=>item.id===303).status,'PENDING')
 await assert.rejects(residentAgain.load('src/api/admin.ts').updateAdminSlot(1008,{is_active:true}),e=>e.status===403)
 residentAgain.load('src/api/guestMode.ts').startGuestDemo('ADMIN')
 const adminAgain=runtime(false,forbiddenFetch,storage)
 assert.equal((await adminAgain.load('src/api/auth.ts').getMe()).name,'관리자 진행 상태')
 assert.equal((await adminAgain.load('src/api/admin.ts').listAdminShareRequests(3)).items.find(item=>item.id===303).status,'REJECTED')
 assert.equal((await adminAgain.load('src/api/admin.ts').listAdminSlots(3)).items.find(item=>item.slot_id===1008).is_active,true)
 assert.equal(storage.get('chagok.auth'),'real-session-sentinel')
})

test('existing resident storage and invalid saved role retain resident behavior',async()=>{
 const storage=guestStorage(),legacy=runtime(false,forbiddenFetch,storage)
 await legacy.load('src/api/auth.ts').updateMe({name:'기존 입주민'})
 await legacy.load('src/api/sharedParking.ts').previewGuestShareResult(701,'REJECTED')
 storage.set('chagok.guest.role.v1','invalid')
 const restored=runtime(false,forbiddenFetch,storage)
 assert.equal(restored.load('src/api/guestMode.ts').GUEST_ROLE,'RESIDENT')
 assert.equal(restored.load('src/api/guestMode.ts').GUEST_SESSION_KEY,'chagok.guest.session.v1')
 assert.equal((await restored.load('src/api/auth.ts').getMe()).name,'기존 입주민')
 assert.equal((await restored.load('src/api/sharedParking.ts').getShareRequest(701)).status,'REJECTED')
 await assert.rejects(restored.load('src/api/admin.ts').getAdminDashboard(3),e=>e.status===403)
})
