import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded'
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded'
import NotificationsRoundedIcon from '@mui/icons-material/NotificationsRounded'
import { Box, Button, Divider, Stack, Typography } from '@mui/material'
import ParkingMap from '../components/ParkingMap'
import { NavButton, PageTitle, SectionTitle, StatusChip, Surface } from '../components/Ui'
import { tones } from '../theme'

export default function AdminPage() {
  return <Stack gap={2.25}><PageTitle eyebrow="관리자" title="월계 햇빛빌라" description="주차 구역과 이웃 요청을 한곳에서 관리해요." action={<Button size="small" startIcon={<NotificationsRoundedIcon/>}>알림 2</Button>}/><Surface sx={{bgcolor:'#F8FAFD'}}><Stack gap={1.25}><Stack direction="row" justifyContent="space-between"><div><Typography variant="subtitle2">공유 사용 요청</Typography><Typography variant="caption" color="text.secondary">방금 · 햇살빌라 A-1</Typography></div><StatusChip kind="pending"/></Stack><Divider/><Stack direction="row" gap={1}><Button component="a" href="#request-rejected" variant="outlined" color="error" fullWidth>거절</Button><Button component="a" href="#request-accepted" variant="contained" fullWidth>수락</Button></Stack></Stack></Surface><SectionTitle action={<StatusChip kind="available" label="주차 가능 3곳"/>}>실시간 주차 구역</SectionTitle><ParkingMap compact/><Stack direction="row" gap={0.75} flexWrap="wrap"><StatusChip kind="available"/><StatusChip kind="external"/><StatusChip kind="danger" label="미확인 차량"/></Stack><Surface><Typography variant="subtitle2">주차 혼잡도</Typography><Typography variant="caption" color="text.secondary">최근 7일 · 가장 붐빈 시간의 점유 칸 수</Typography><Box sx={{height:112,display:'flex',alignItems:'flex-end',gap:1,mt:2}}>{[54,76,48,92,72,62,42].map((height,index)=><Box key={index} sx={{height:`${height}%`,flex:1,bgcolor:index===3?'primary.main':'#BBD0FF',borderRadius:'6px 6px 2px 2px'}}/>)}</Box><Stack direction="row" justifyContent="space-around" mt={0.5}>{['월','화','수','목','금','토','일'].map((day)=><Typography key={day} variant="caption" color="text.secondary">{day}</Typography>)}</Stack></Surface><Surface sx={{bgcolor:'#F1F7FF',borderColor:'#D5E5FF'}}><Stack direction="row" gap={1.25}><AutoAwesomeRoundedIcon sx={{color:tones.blue}}/><div><Typography variant="subtitle2">AI 분석 · 향후 제공</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>금요일과 월요일은 평균 한 칸 이상 여유가 있어 공유 자리로 열기 좋아요.</Typography></div></Stack></Surface><SectionTitle>관리 메뉴</SectionTitle>{[['공유 요청 관리','대기 요청을 검토하고 승인·거절','requests'],['주차 구역 설정','칸별 상태와 위치 관리','slots'],['차고지 등록','새 공유 공간 추가','garage-register']].map(([title,desc,to])=><Surface key={title}><Box component="a" href={`#${to}`} sx={{display:'flex',justifyContent:'space-between',alignItems:'center',color:'inherit'}}><div><Typography variant="subtitle2">{title}</Typography><Typography variant="caption" color="text.secondary">{desc}</Typography></div><ArrowForwardRoundedIcon color="action"/></Box></Surface>)}<NavButton to="home" variant="text" fullWidth>입주민 화면으로 보기</NavButton></Stack>
}
